### ISSUE TITLE
dialog弹窗不显示的问题

### ISSUE THREAD

**Issue by wangjiatao111** [pure-admin/pure-admin-utils-docs#10]
![image](https://github.com/pure-admin/pure-admin-utils-docs/assets/68986265/f98ca1ec-c494-4d36-84d7-4edc656128e9)
目前下载的最新源码，无做修改，这里弹窗不显示，控制台也无报错

**Comment by xiaoxian521** [comment]
这个问题属于这里 https://github.com/pure-admin/vue-pure-admin
用户管理还在完善 https://github.com/pure-admin/vue-pure-admin/issues/428
