### ISSUE TITLE
打包计算 utils.getPackageSize 的方法计算出的值有疑问

### ISSUE THREAD

**Issue by wuhaohuang** [pure-admin/pure-admin-utils-docs#11]
控制台输出的是 恭喜打包完成（总用时00分10秒，打包后的大小为3.11 MB），但用文件夹直接查看属性是5.6M。
是计算错误？还是某些文件是不计入计算的？

**Comment by xiaoxian521** [comment]
获取指定文件夹中所有文件的总大小

根据我们的测试 它的计算是完全正确的 可能是你使用方式问题，请具体检查代码
