### ISSUE TITLE
希望加多关于tree的几个util

### ISSUE THREAD

**Issue by wintsa123** [pure-admin/pure-admin-utils-docs#12]
比如treeToArrayNode/ArrayNodeToTree,自适应匹配广度深度搜索。。。

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/vue-pure-admin/blob/main/src/utils/tree.ts

**Comment by wintsa123** [comment]
@xiaoxian521 大佬为啥不放在pure-admin-utils这个仓库。。。

**Comment by xiaoxian521** [comment]
有 你调用就行
