### ISSUE TITLE
关于priceToThousands的需求

### ISSUE THREAD

**Issue by PeyFon** [pure-admin/pure-admin-utils-docs#13]
能否给priceToThousands这个函数增加个参数，让我指定小数位数。比如 0  或者3 位小数

**Comment by xiaoxian521** [comment]
已支持 https://github.com/pure-admin/pure-admin-utils-docs/commit/f114aa77dc39a46a94c6f6951cffeeec7b7c7f74
更新版本至 `1.9.9` 即可

**Comment by xiaoxian521** [comment]
升级到 1.9.10 版本
