### ISSUE TITLE
乘法multiplication 部分情况仍精度丢失

### ISSUE THREAD

**Issue by marc021** [pure-admin/pure-admin-utils-docs#18]
例如multiplication(1.4003, 100)

**Comment by xiaoxian521** [comment]
感谢反馈 稍后修复

**Comment by xiaoxian521** [comment]
升级到 `2.4.5` 版本，已修复
随便说一句，如果需要确保精度高度准确，可以使用第三方库，如 `decimal.js` 或 `big.js`

**Comment by marc021** [comment]
除法 divisionOperation也存在精度丢失问题，e.g. divisionOperation(18778.67, 10000) v2.4.7存在此问题，如果可以的话麻烦修复一下，感谢 @xiaoxian521

**Comment by xiaoxian521** [comment]
<img width="605" alt="image" src="https://github.com/pure-admin/pure-admin-utils-docs/assets/44761321/b01eb98e-6f9f-42b4-894e-84e4cb9ad519">
