### ISSUE TITLE
在.ts文件中引入时  提示 《找不到模块“@pureadmin/utils”或其相应的类型声明 》有时间可以优化下哈哈 

### ISSUE THREAD

**Issue by leoiris123** [pure-admin/pure-admin-utils-docs#19]
大佬的这份文档是我见过的最详细的文档了

**Comment by xiaoxian521** [comment]
无法复现 可以参考https://github.com/pure-admin/vue-pure-admin
估计是你的`tsconfig.json`配置问题

**Comment by xiaoxian521** [comment]
<img width="1525" alt="image" src="https://github.com/pure-admin/pure-admin-utils-docs/assets/44761321/b9b59efc-587a-4e1e-b400-b34dc0c0f5f6">
<img width="760" alt="image" src="https://github.com/pure-admin/pure-admin-utils-docs/assets/44761321/fd7c2c20-0eb3-49bd-bf5b-c3fdc55b1661">
