### ISSUE TITLE
getKeyList 方法，若key的值存在0，则数值0会被忽略

### ISSUE THREAD

**Issue by nineaiyu** [pure-admin/pure-admin-utils-docs#21]
![image](https://github.com/pure-admin/pure-admin-utils-docs/assets/19207867/c2e8777b-d8fc-4229-b9ae-cc8c72c25128)

**Comment by xiaoxian521** [comment]
能把示例代码贴出来不
方便处理

**Comment by xiaoxian521** [comment]
升级最新版 2.4.6 已解决
