### ISSUE TITLE
时间戳转换为正常时间

### ISSUE THREAD

**Issue by shuai1999** [pure-admin/pure-admin-utils-docs#22]
时间戳转换为正常时间

**Comment by xiaoxian521** [comment]
嘿 可以用dayjs 哈
一般我们这个工具里用的都是dayjs没有的 或实现起来麻烦的

**Comment by shuai1999** [comment]
> 嘿可以用dayjs哈 一般我们这个工具里用的都是dayjs没有的或者实现起来麻烦的

好的呢 谢谢
