### ISSUE TITLE
多个图表在一个页面如何去渲染

### ISSUE THREAD

**Issue by DaYang816** [pure-admin/pure-admin-utils-docs#27]
请作者大大为什么在渲染图表的时候不能写在里面？
![image](https://github.com/pure-admin/pure-admin-utils-docs/assets/43984550/ea182ca8-d176-476e-8418-a9e8ee6da294)
写在里面会报错，报错如下
![image](https://github.com/pure-admin/pure-admin-utils-docs/assets/43984550/19c244ff-8572-40f4-8fe7-a057a33ac109)
只能这么写在外面么，多个图表只能封装起来了么？
![image](https://github.com/pure-admin/pure-admin-utils-docs/assets/43984550/9f6b4ff7-4414-4123-bc22-14711a600411)

麻烦作者了

**Comment by xiaoxian521** [comment]
只解决bug 自行研究
