### ISSUE TITLE
@pureadmin/utils

### ISSUE THREAD

**Issue by codebabydxj** [pure-admin/pure-admin-utils-docs#5]
大佬，这个工具包不对外开放吗，想看看源码~~

**Comment by xiaoxian521** [comment]
预计年底开源

**Comment by codebabydxj** [comment]
工具包 水印加上 我在控制台可以删除元素就没用了， 是否可以加个控制锁什么的，类似定时器

**Comment by xiaoxian521** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/44761321/217430646-591278fd-86aa-4c45-b8c2-6f11b5ee22b8.png">
细看文档
