### ISSUE TITLE
pure-admin-utils

### ISSUE THREAD

**Issue by superdl1996** [pure-admin/pure-admin-utils-docs#7]
大佬  ,pure-admin-utils  有可以观看源码地址吗

**Comment by xiaoxian521** [comment]
不好意思 目前作为一种激励 只面向 `pure` 成员开源

**Comment by xiaoxian521** [comment]
后面平台计划开发可视化大屏和`App` 还是有机会加入 `pure`成为一员的

**Comment by xiaoxian521** [comment]
对于安全方便大家完全不用担心，这里保证其绝对安全

当然你也可以查看压缩的源码，源码不多 也很容易查看 

<img width="1471" alt="image" src="https://github.com/pure-admin/pure-admin-utils-docs/assets/44761321/22f0b79e-0414-4e9c-96b0-465fd49766d2">

**Comment by xiaoxian521** [comment]
对于 `pure-admin-utils` 的维护我们是很及时的，如果使用中遇到 `pure-admin-utils` 的 `bug` 及时在 https://github.com/pure-admin/vue-pure-admin/issues 这里提 `issues` 我们确定是 `bug` 后会及时修复并发版
