### ISSUE TITLE
useECharts 图表类型支持不全

### ISSUE THREAD

**Issue by zijol** [pure-admin/pure-admin-utils-docs#9]
useECharts，当前还不支持散点图等。

使用时报错信息如下：
[ECharts] Series scatter is used but not imported.
import { ScatterChart } from 'echarts/charts';
echarts.use([ScatterChart]);

**Comment by xiaoxian521** [comment]
按需导入 `useECharts` 不负责倒入 并没有完整引入所有图表类型 它只负责渲染
